name: iron build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_iron:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:jammy
    steps:
      - name: cancle preivious run
        uses: styfle/cancel-workflow-action@0.11.0
      - name: setup ROS2
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: iron
      - name: Install dependencies
        run: pip install black
      - name: ROS2 build and test
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          import-token: ${{ secrets.GITHUB_TOKEN }}
          target-ros2-distro: iron
